<a href="https://colab.research.google.com/github/AhmedAbdoulahi/DataScience/blob/master/numpy_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Une courte introduction à Numpy et au broadcasting**

In [ ]:
import numpy as np

In [ ]:
#Ensuite, vous pouvez utiliser Numpy pour générer des matrices ou des vecteurs. Par exemple, numpy.random.rand
#vous permet de générer des matrices de nombres aléatoires :
r = np.random.rand(3, 7)
print(r)
print(type(r))


[[0.64927178 0.77028149 0.28418568 0.652533   0.06735838 0.57332735
  0.35700662]
 [0.3472824  0.06781286 0.39267646 0.40999177 0.66067511 0.56975237
  0.98750615]
 [0.65188794 0.59642676 0.4157503  0.21366459 0.10436535 0.65384479
  0.21789926]]
<class 'numpy.ndarray'>


In [ ]:
a = np.random.rand(1,2)
print(a)

[[0.15045137 0.12784279]]


On peut accéder aux éléments d'un ndarray comme s'ils s'agissaient d'éléments d'une liste. Il est
aussi possible de faire des slices d'une telle structure. Regardez la documentation des fonctions zeros et
ones de la librairie numpy, permettant de générer des tableaux Numpy.
Les tableaux Numpy ont une taille
xe, et "sortir" d'un tableau provoquera une exception :

In [ ]:
t = r[:,:2]
print(t)

[[0.64927178 0.77028149]
 [0.3472824  0.06781286]
 [0.65188794 0.59642676]]


In [ ]:
r[5,5] = 0 #provoque une exception si on depasse le nbre d'elements

In [ ]:
#On peut récupérer la taille d'un ndarray sous forme de tuple grâce à l'attribut shape :
taille = r.shape
print(taille)
print(type(taille))

(3, 7)
<class 'tuple'>


Opérations entre matrices de tailles diérentes
Les matrices et vecteurs de Numpy permettent d'utiliser le principe du broadcasting. Pour expliquer ce
dernier (qui ne fonctionne qu'avec les matrices Numpy - inutile d'essayer avec les séquences et collections
de base de Python), considérons l'exemple suivant

NB: si les deux matrices sont de taille differentes alors une exception est leve

In [ ]:
s = np.random.randint(0,3,[3,2])
t = np.random.randint(4,6,[1,2])
f = s+t


In [ ]:
print("La matrice r vaut")
print(s)
print()
print("La matrice s vaut")
print(t)
print()
print("La matrice f vaut")
print(f)
print()


La matrice r vaut
[[2 0]
 [0 0]]

La matrice s vaut
[[4 5]
 [5 4]]

La matrice f vaut
[[6 5]
 [5 4]]



In [ ]:
import numpy
#On crée deux matrices de nombres aléatoires entre 0 et 9, de tailles différentes( mais compatible pour le broadcasting, ajuste la forme du tableau en prenant le petit )
#le broadcasting joue sur les dimensions temporairement, en parcourant et en ajustant pour avoir le meme shape,
r = numpy.random.randint(0, 9, [1, 7])
s = numpy.random.randint(0, 9, [5, 7])
f = r+s
print("La matrice r vaut")
print(r)
print()
print(s)
print()
print("La matrice f vaut")
print(f)
print()


La matrice r vaut
[[3 4 5 4 0 0 2]]

[[1 0 5 5 5 2 6]
 [6 1 5 8 2 6 4]
 [8 7 6 4 1 4 8]
 [0 8 0 8 6 5 0]
 [0 3 3 7 2 5 4]]

La matrice f vaut
[[ 4  4 10  9  5  2  8]
 [ 9  5 10 12  2  6  6]
 [11 11 11  8  1  4 10]
 [ 3 12  5 12  6  5  2]
 [ 3  7  8 11  2  5  6]]



In [ ]:
#On crée deux matrices de nombres aléatoires entre 0 et 9
r = numpy.random.randint(0, 9, [3, 1])
s = numpy.random.randint(0, 9, [1, 4])
f = r*s
print("La matrice r vaut")
print(r)
print()
print("La matrice s vaut")
print(s)
print()
print("La matrice f vaut")
print(f)
print()

La matrice r vaut
[[7]
 [1]
 [8]]

La matrice s vaut
[[4 2 0 3]]

La matrice f vaut
[[28 14  0 21]
 [ 4  2  0  3]
 [32 16  0 24]]



In [ ]:
# si c'est pas des entiers on utilise uniquement rand au lieu de randint
s = np.random.rand(3,3)
t = np.random.rand(3,3)
f = s+t

print("La matrice r vaut")
print(s)
print()
print("La matrice s vaut")
print(t)
print()
print("La matrice f vaut")
print(f)
print()

La matrice r vaut
[[0.64869605 0.32966177 0.37380881]
 [0.18949994 0.05731323 0.89900395]
 [0.80644817 0.37257325 0.21816954]]

La matrice s vaut
[[0.43192404 0.68046875 0.58146408]
 [0.64387309 0.06823577 0.83505633]
 [0.20850923 0.49387261 0.4072546 ]]

La matrice f vaut
[[1.08062009 1.01013051 0.95527289]
 [0.83337303 0.12554901 1.73406028]
 [1.0149574  0.86644586 0.62542414]]

