<a href="https://colab.research.google.com/github/AhmedAbdoulahi/DataScience/blob/master/tp1_IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TP1 : Programmation IA

In [ ]:
#1 afficher un tab comme en C (beurk!)

tab = ['a', 2, 3.14]
for i in range(0,len(tab)):
  print(tab[i])

a
2
3.14


In [ ]:
print('bonjour tout le monde')

bonjour tout le monde


In [ ]:
#2 toujours C mais en utilisant les arguments prédéfinis (beurk aussi)
for i in range(len(tab)):
  print(tab[i])

a
2
3.14


In [ ]:
tab

['a', 2, 3.14]

In [ ]:
# python!
for e in tab:
  print(e)

a
2
3.14


In [ ]:
# definition
def print_hello(user):
  print('hello ' + user)

# utilisation
print_hello('Sam')


hello Sam


In [ ]:
def retourne(tab): # inverse un tableau
  if tab == []:
    return []
  else:  # concatenation (+) de
    # 1. 'retourne' appliquee a tab sans le 1er element
    # 2. le tableau constitué uniquement du premier element de tab
    return retourne(tab[1:]) + tab[:1]


# utilisation
retourne ([1,2,3])

[3, 2, 1]

In [ ]:
def tri_rapide(tab):
  if tab == []:
    return []
  else:
    pivot = tab[0]
    # on selectionne les elements plus petits que pivot
    pp = [x for x in tab[1:] if x < pivot]
    # on selectionne les elements plus grands que pivot
    pg = [x for x in tab[1:] if x > pivot]
    return tri_rapide(pp) + [pivot] + tri_rapide(pg)

## Exercice

Définir une fonction 'fib' qui calcule la valeur de la suite de Fibonacci pour l'entier passé en paramètre


In [ ]:
#code fibonacci
def fib(a):
  if a == 2 :
    return 1 ;
  return fib(a-1) + fib(a-2)


# Pytorch

Bibliothèque pour le calcul scientifique (à la Matlab...) orientée pour l'apprentissage automatique et les rééseaux de neurones

Pour l'utiliser, il faut commencer par l'importer avec la directive *import*. En python on doit préfixer les fonctions d'un module par le nom de ce module. En pratique on renomme le nom du module pour quelque chose de plus court. Ici, on renomme *torch* en *t*, et toutes les fonctions de cette bibliothèque devront être précédées par *t.* (t suivi de point).

## Vecteurs et matrices

Contrairement aux listes python, *pytorch* permet de définir des vecteurs, des matrices, et plus généralement des tenseurs typés sur lesquels les opérations mathématiques sont efficaces.

- le type *tensor*
 - création à partir d'une liste donnera un vecteur


In [ ]:
import torch as t

print(t.__version__)

2.0.1+cu118


In [ ]:
#ici on aura un vecteur d'entiers (car tous les éléments sont entiers)
a = t.tensor([3,2,1])
print(a, type(a), a.dtype)

tensor([3, 2, 1]) <class 'torch.Tensor'> torch.int64


In [ ]:
# attention le type des données ne se voit pas sur le type mais sur le dtype
a = t.tensor([3,2,1.0])
print(a, type(a), a.dtype)

tensor([3., 2., 1.]) <class 'torch.Tensor'> torch.float32


In [ ]:
#on peut directement spécifier le dtype
t.tensor([3,2,1], dtype=float)

tensor([3., 2., 1.], dtype=torch.float64)

In [ ]:
m = t.tensor([[1,2,3],[4,5,6]])
print(m, type(m),m.dtype, m.size(), m.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) <class 'torch.Tensor'> torch.int64 torch.Size([2, 3]) torch.Size([2, 3])


- le type tensor
- donnera une matrice à partir d'une liste de listes


In [ ]:
m = t.tensor([[1,2,3],[4,5,6]])
print(m, type(m),m.dtype, m.size(), m.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) <class 'torch.Tensor'> torch.int64 torch.Size([2, 3]) torch.Size([2, 3])


## Fonctions utiles pour créér des tenseurs

In [ ]:
# Un tableau de longueur 10, rempli d'entiers qui valent 0
t.zeros(10, dtype=int)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Une matrice  de taille 3x5 remplie de nombres à virgule flottante de valeur 1
t.ones((3, 5), dtype=float)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

*Policy Iteration*

In [ ]:
import numpy as np

# Définition du MDP (Markov Decision Process)
# - S : ensemble des états
# - A : ensemble des actions
# - P : fonction de transition d'état
# - R : fonction de récompense
# - gamma : facteur de réduction

# 1. Fonction d'initialisation aléatoire de la politique
def initialize_policy(num_states, num_actions):
    return np.random.randint(0, num_actions, num_states)

# Algorithme de Policy Iteration
def policy_iteration(S, A, P, R, gamma, max_iterations=1000):
    num_states = len(S)
    num_actions = len(A)
    policy = initialize_policy(num_states, num_actions)

    for _ in range(max_iterations):
        # Évaluation de la politique actuelle
        V = np.zeros(num_states)
        for s in range(num_states):
            a = policy[s]
            V[s] = sum([P[s][a][s1] * (R[s][a][s1] + gamma * V[s1]) for s1 in range(num_states)])

        policy_stable = True

        # Amélioration de la politique
        for s in range(num_states):
            old_action = policy[s]
            action_values = np.zeros(num_actions)
            for a in range(num_actions):
                action_values[a] = sum([P[s][a][s1] * (R[s][a][s1] + gamma * V[s1]) for s1 in range(num_states)])

            # Sélection de la meilleure action
            best_action = np.argmax(action_values)

            if old_action != best_action:
                policy_stable = False

            policy[s] = best_action

        if policy_stable:
            break

    return policy, V



In [ ]:
# Exemple d'utilisation
if __name__ == "__main__":
    # Définir les ensembles d'états et d'actions, la fonction de transition et la fonction de récompense
    num_states = 3
    num_actions = 2
    S = range(num_states)
    A = range(num_actions)

    # Définition simplifiée d'une fonction de transition et d'une fonction de récompense
    P = np.array([[[0.7, 0.3, 0.0], [0.1, 0.6, 0.3]], [[0.0, 0.8, 0.2], [0.4, 0.4, 0.2]], [[0.0, 0.0, 1.0], [0.0, 0.0, 1.0]]])
    R = np.array([[[1.0, -1.0, 0.0], [-1.0, 1.0, 0.0]], [[2.0, -1.0, 0.0], [0.0, 0.0, 0.0]], [[0.0, 0.0, 10.0], [0.0, 0.0, 10.0]]])

    gamma = 0.9

    # Exécuter l'algorithme de Policy Iteration
    optimal_policy, optimal_values = policy_iteration(S, A, P, R, gamma)

    print("Politique optimale :", optimal_policy)
    print("Valeurs optimales :", optimal_values)


Politique optimale : [1 1 0]
Valeurs optimales : [ 0.5   0.18 10.  ]
